name: EC2
on: [push, pull_request]
jobs:
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Configure SSH
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
      - name: Stop the server
        run: ssh staging 'sudo systemctl stop devops.service'
      - name: Check out the source
        run: ssh staging 'cd devops_demo && git fetch && git reset --hard origin/master'
      - name: Start the server
        if: ${{ always() }}
        run: ssh staging 'sudo systemctl start devops.service'
