name: Django CI/CD workflow
on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main
jobs:
  test_job:
    name: runs django test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: devops
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Check Python version
        run: python --version
      - name: Install pipenv
        run: pip install pipenv
      - name: Install requirements # install application requirements
        run: pipenv install --system
      - name: Run DB Migrate
        run: sh build/migrate.sh
      - name: Run Test # running tests
        run: sh build/test.sh
