name: Django CI/CD workflow
on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main
jobs:
  test-job:
    runs-on: ubuntu-latest
  steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python environment 
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Check Python version
        run: python --version
      - name: Install requirements # install application requirements
        run: pipenv install --system
      - name: Run Test # running tests
        run: python manage.py test      